ci: Use Windows runner instead of Ubuntu runner with cross for x86_64-pc-windows-gnu build
Windows runner should be used for this target.

```
error: linking with `x86_64-w64-mingw32-gcc` failed: exit status: 1
  |
  = note:  "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "/tmp<sysroot>cpl8J31/symbols.o" "<2 object files omitted>" "-Wl,-Bstatic" "<sysroot>/lib/rustlib/x86_64-pc-windows-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,libcfg_if-*,libwindows_targets-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,liblibc-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lkernel32" "-lkernel32" "-lkernel32" "-lntdll" "-luserenv" "-lws2_32" "-ldbghelp" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmingwex" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-o" "/target/x86_64-pc-windows-gnu/release/deps/test_crate-8232c8178f15a8ce.exe" "-Wl,--gc-sections" "-no-pie" "-Wl,-O1" "-Wl,--strip-debug" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          /rust/lib/rustlib/x86_64-pc-windows-gnu/lib/libstd-c8d0fbc527175d1d.rlib(std-c8d0fbc527175d1d.std.24564e7b916de01e-cgu.0.rcgu.o):/rustc/254b59607d4417e9dffbc307138ae5c86280fe4c/library\std\src\sys\net\hostname/windows.rs:15: undefined reference to `GetHostNameW'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)
```